// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKCPgH3hcj3vZrHR5qrlSQdPL7zjYG1Eo',
    appId: '1:289836889647:web:c54dbcfe85326b107ef8da',
    messagingSenderId: '289836889647',
    projectId: 'flutterapp-techm',
    authDomain: 'flutterapp-techm.firebaseapp.com',
    storageBucket: 'flutterapp-techm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWs12FvNnUPyrKu_y0lj6eeuEStSg3m8',
    appId: '1:289836889647:android:8d3c72e8e29472e47ef8da',
    messagingSenderId: '289836889647',
    projectId: 'flutterapp-techm',
    storageBucket: 'flutterapp-techm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuUvfsiAKciwRmObxGvPQIIBSbZininI',
    appId: '1:289836889647:ios:db97ef517b4fc3637ef8da',
    messagingSenderId: '289836889647',
    projectId: 'flutterapp-techm',
    storageBucket: 'flutterapp-techm.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuUvfsiAKciwRmObxGvPQIIBSbZininI',
    appId: '1:289836889647:ios:db97ef517b4fc3637ef8da',
    messagingSenderId: '289836889647',
    projectId: 'flutterapp-techm',
    storageBucket: 'flutterapp-techm.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKCPgH3hcj3vZrHR5qrlSQdPL7zjYG1Eo',
    appId: '1:289836889647:web:eb102e5d73685b0e7ef8da',
    messagingSenderId: '289836889647',
    projectId: 'flutterapp-techm',
    authDomain: 'flutterapp-techm.firebaseapp.com',
    storageBucket: 'flutterapp-techm.firebasestorage.app',
  );
}
